# Generated by Django 4.0 on 2022-01-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='botUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=8)),
                ('user_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bot_users',
            },
        ),
    ]
