# Generated by Django 4.0 on 2022-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userIdentifierByLink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='botUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bot_user',
            },
        ),
        migrations.DeleteModel(
            name='botUsers',
        ),
    ]
