# Generated by Django 4.0 on 2022-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userIdentifierByLink', '0002_botuser_delete_botusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='incorrectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'incorrect_link',
            },
        ),
    ]
