# Generated by Django 4.0 on 2022-01-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userIdentifierByLink', '0004_incorrectlink_chat_id_incorrectlink_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectlink',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
